FROM ubuntu:17.10

#run apt-get update && apt-get install -y nodejs npm  build-essential python git \
#&& mkdir source && mkdir voting && mkdir node_modules \
#&& npm install ganache-cli web@0.20.2 solc
